### PR TITLE
RenameSuggestion

### PR DESCRIPTION
**Pull request by AnonymousAccount4SE**
see issue #52 cited.

### CODE REVIEW

**Comment by oswaldobapvicjr** [comment]
This PR will be canceled for it addresses no practical improvement. More details can be found in the linked issue (#52).

**Review by oswaldobapvicjr — COMMENTED** [review]
The suggested name "parseString2TimeInterval" is redundant: the method accepts a String and returns a TimeInterval, so there's no point in repeating the parameter and return type in the method name. It just makes the coding mode verbose.

**Comment by oswaldobapvicjr** [comment]
@AnonymousAccount4SE, here are the reasons why your change is not approved:

The suggested name parseString2TimeInterval is redundant: by looking at the method signature, anyone can understand that the method accepts a String and returns a TimeInterval, so there's no point in repeating the parameter and return type in the method name. It just makes the coding mode verbose.
The method contains a Javadoc with some examples of accepted strings. So, your statement that the API users will have to look inside the method to understand what it does is not true. Every good IDE available in the community (e.g.: Eclipse, IntelliJ, etc.) will display the Javadoc when the user rests the mouse on the method name (here's the compiled Javadoc of the TimeInterval class: https://javadoc.io/static/net.obvj/agents/0.3.3/net/obvj/agents/util/TimeInterval.html)
The current method name is inspired by other well-known classes designed by leading programmers of the Java API. Here you have just a few examples:
Duration.of(...)
Instant.of(...)
LocalDateTime.of(...)
Stream.of(...)
Optional.of(...)
CompletableFuture.of(...)
Renaming a public method is not a simple task. Because this project is released on Maven Central, it may be a dependency for other projects too. So you don't just rename the method. Instead, you must deprecate it, and create a new one. That way, other API users will be notified that the old method may be removed soon, without breaking their code.
Good luck!

**Comment by AnonymousAccount4SE** [comment]
That is reasonable, thanks!

**Pull request closed without merging**
